name: Welcome First-Time Contributors

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome to the project! Thanks for opening your first issue. We're excited to have you here!"
          pr-message: "🎉 Thank you for your first pull request! We appreciate your contribution. Please check our contribution guidelines if you haven't already."
